-- Expected frontend contract views for TravelCast AviatorGraf Prep
-- Copy/adapt into sql/live_views.sql after core schema exists.

create or replace view v_airport_status_dashboard as
select
  airport_id,
  iata,
  icao,
  region,
  display_name,
  airport_name,
  city,
  state,
  latitude,
  longitude,
  dominant_sky_condition,
  high_temperature_f,
  low_temperature_f,
  forecast_impact_color,
  forecast_impact_label,
  forecast_impact_reasons,
  forecast_icon_id,
  forecast_icon_url,
  current_delay_type,
  current_status_code,
  current_reason,
  avg_delay_minutes,
  max_delay_minutes,
  delay_summary,
  arrival_runway,
  departure_runway,
  aar,
  metar_condition,
  flight_category,
  metar_wind,
  metar_visibility,
  metar_observed_at,
  taf_trend,
  taf_next_risk_window,
  overall_impact_color,
  overall_impact_label,
  last_updated_at,
  freshness_status,
  source_summary
from airport_status_snapshots;
