export const sampleAirportStatus = [
  {
    "airport_id": "KDEN",
    "iata": "DEN",
    "icao": "KDEN",
    "region": "Rocky Mountains",
    "display_name": "Denver",
    "airport_name": "Denver International Airport",
    "city": "Denver",
    "state": "CO",
    "latitude": 39.8561,
    "longitude": -104.6737,
    "dominant_sky_condition": "Thunderstorms",
    "high_temperature_f": 74,
    "low_temperature_f": 52,
    "forecast_impact_color": "Red",
    "forecast_impact_label": "Major Issues Possible",
    "forecast_impact_reasons": "Thunderstorms may reduce arrival throughput.",
    "forecast_icon_id": "04",
    "forecast_icon_url": "",
    "current_delay_type": "Ground Delay Program",
    "current_status_code": "GROUND_DELAY_PROGRAM",
    "current_reason": "Weather / Thunderstorms",
    "avg_delay_minutes": 63,
    "max_delay_minutes": 386,
    "delay_summary": "GDP active. Avg delay 63 min, maximum delay 386 min.",
    "arrival_runway": "16L/16R/17R",
    "departure_runway": "",
    "aar": 64,
    "metar_condition": "TSRA",
    "flight_category": "IFR",
    "metar_wind": "22015G28KT",
    "metar_visibility": "3SM",
    "metar_observed_at": "2026-06-02T22:10:00Z",
    "taf_trend": "Thunderstorms possible this evening",
    "taf_next_risk_window": "2100Z-0300Z",
    "overall_impact_color": "Red",
    "overall_impact_label": "Current Operational Impact",
    "last_updated_at": "2026-06-02T22:10:00Z",
    "freshness_status": "fresh",
    "source_summary": "Current Operational Impact \u2014 FAA NAS Status; Forecast Weather Impact \u2014 NWS forecast proxy; Aviation Weather Truth \u2014 AviationWeather METAR/TAF"
  },
  {
    "airport_id": "KDFW",
    "iata": "DFW",
    "icao": "KDFW",
    "region": "Southern Plains",
    "display_name": "Dallas/Fort Worth",
    "airport_name": "Dallas Fort Worth International Airport",
    "city": "Dallas",
    "state": "TX",
    "latitude": 32.8998,
    "longitude": -97.0403,
    "dominant_sky_condition": "Partly Cloudy",
    "high_temperature_f": 88,
    "low_temperature_f": 70,
    "forecast_impact_color": "Amber",
    "forecast_impact_label": "Monitor",
    "forecast_impact_reasons": "Scattered storms possible near terminal airspace.",
    "forecast_icon_id": "30",
    "forecast_icon_url": "",
    "current_delay_type": "None",
    "current_status_code": "NORMAL",
    "current_reason": "No active FAA/NAS event in demo data",
    "avg_delay_minutes": null,
    "max_delay_minutes": null,
    "delay_summary": "No active operational impact in demo data.",
    "arrival_runway": "18R/17C",
    "departure_runway": "18L/17R",
    "aar": 92,
    "metar_condition": "VFR",
    "flight_category": "VFR",
    "metar_wind": "17012KT",
    "metar_visibility": "10SM",
    "metar_observed_at": "2026-06-02T22:10:00Z",
    "taf_trend": "VFR, thunder risk later",
    "taf_next_risk_window": "After 2300Z",
    "overall_impact_color": "Amber",
    "overall_impact_label": "Forecast Weather Impact",
    "last_updated_at": "2026-06-02T22:10:00Z",
    "freshness_status": "fresh",
    "source_summary": "Forecast Weather Impact \u2014 NWS forecast proxy"
  },
  {
    "airport_id": "KATL",
    "iata": "ATL",
    "icao": "KATL",
    "region": "Southeast",
    "display_name": "Atlanta",
    "airport_name": "Hartsfield-Jackson Atlanta International Airport",
    "city": "Atlanta",
    "state": "GA",
    "latitude": 33.6367,
    "longitude": -84.4281,
    "dominant_sky_condition": "Scattered Thunderstorms",
    "high_temperature_f": 84,
    "low_temperature_f": 68,
    "forecast_impact_color": "Amber",
    "forecast_impact_label": "Possible Delays",
    "forecast_impact_reasons": "Thunderstorm language in forecast.",
    "forecast_icon_id": "38",
    "forecast_icon_url": "",
    "current_delay_type": "None",
    "current_status_code": "NORMAL",
    "current_reason": "No active FAA/NAS event in demo data",
    "avg_delay_minutes": null,
    "max_delay_minutes": null,
    "delay_summary": "No active operational impact in demo data.",
    "arrival_runway": "",
    "departure_runway": "",
    "aar": null,
    "metar_condition": "VFR",
    "flight_category": "VFR",
    "metar_wind": "21008KT",
    "metar_visibility": "10SM",
    "metar_observed_at": "2026-06-02T22:10:00Z",
    "taf_trend": "VCTS possible",
    "taf_next_risk_window": "Evening",
    "overall_impact_color": "Amber",
    "overall_impact_label": "Forecast Weather Impact",
    "last_updated_at": "2026-06-02T22:10:00Z",
    "freshness_status": "fresh",
    "source_summary": "Forecast Weather Impact \u2014 NWS forecast proxy"
  },
  {
    "airport_id": "KMIA",
    "iata": "MIA",
    "icao": "KMIA",
    "region": "Florida",
    "display_name": "Miami",
    "airport_name": "Miami International Airport",
    "city": "Miami",
    "state": "FL",
    "latitude": 25.7959,
    "longitude": -80.287,
    "dominant_sky_condition": "Showers",
    "high_temperature_f": 86,
    "low_temperature_f": 76,
    "forecast_impact_color": "Amber",
    "forecast_impact_label": "Monitor",
    "forecast_impact_reasons": "Showers and tropical moisture may affect throughput.",
    "forecast_icon_id": "11",
    "forecast_icon_url": "",
    "current_delay_type": "Departure Delay",
    "current_status_code": "DELAY",
    "current_reason": "Volume / Multi-taxi",
    "avg_delay_minutes": 15,
    "max_delay_minutes": 30,
    "delay_summary": "Departure delay avg 15 min in demo data.",
    "arrival_runway": "09/12",
    "departure_runway": "08R/12",
    "aar": 44,
    "metar_condition": "SHRA",
    "flight_category": "MVFR",
    "metar_wind": "10014KT",
    "metar_visibility": "6SM",
    "metar_observed_at": "2026-06-02T22:10:00Z",
    "taf_trend": "Showers nearby",
    "taf_next_risk_window": "All afternoon",
    "overall_impact_color": "Amber",
    "overall_impact_label": "Operational Delay",
    "last_updated_at": "2026-06-02T22:10:00Z",
    "freshness_status": "fresh",
    "source_summary": "Current Operational Impact \u2014 FAA NAS Status"
  },
  {
    "airport_id": "KSFO",
    "iata": "SFO",
    "icao": "KSFO",
    "region": "West Coast",
    "display_name": "San Francisco",
    "airport_name": "San Francisco International Airport",
    "city": "San Francisco",
    "state": "CA",
    "latitude": 37.6213,
    "longitude": -122.379,
    "dominant_sky_condition": "Low Clouds",
    "high_temperature_f": 62,
    "low_temperature_f": 54,
    "forecast_impact_color": "Amber",
    "forecast_impact_label": "Ceiling Monitor",
    "forecast_impact_reasons": "Low clouds/ceilings possible.",
    "forecast_icon_id": "26",
    "forecast_icon_url": "",
    "current_delay_type": "Ground Delay Program",
    "current_status_code": "GROUND_DELAY_PROGRAM",
    "current_reason": "Other / Low ceiling demo context",
    "avg_delay_minutes": 65,
    "max_delay_minutes": 120,
    "delay_summary": "GDP demo record.",
    "arrival_runway": "28L/28R",
    "departure_runway": "28L/28R",
    "aar": 36,
    "metar_condition": "BKN008",
    "flight_category": "IFR",
    "metar_wind": "28012KT",
    "metar_visibility": "8SM",
    "metar_observed_at": "2026-06-02T22:10:00Z",
    "taf_trend": "Low clouds",
    "taf_next_risk_window": "Morning/evening",
    "overall_impact_color": "Red",
    "overall_impact_label": "Current Operational Impact",
    "last_updated_at": "2026-06-02T22:10:00Z",
    "freshness_status": "fresh",
    "source_summary": "Current Operational Impact \u2014 FAA NAS Status"
  },
  {
    "airport_id": "KLAS",
    "iata": "LAS",
    "icao": "KLAS",
    "region": "Desert Southwest",
    "display_name": "Las Vegas",
    "airport_name": "Harry Reid International Airport",
    "city": "Las Vegas",
    "state": "NV",
    "latitude": 36.084,
    "longitude": -115.1537,
    "dominant_sky_condition": "Sunny",
    "high_temperature_f": 98,
    "low_temperature_f": 76,
    "forecast_impact_color": "Green",
    "forecast_impact_label": "Good",
    "forecast_impact_reasons": "No major weather-impact language detected.",
    "forecast_icon_id": "32",
    "forecast_icon_url": "",
    "current_delay_type": "Airport Closure",
    "current_status_code": "CLOSURE",
    "current_reason": "GA restriction demo freeform",
    "avg_delay_minutes": null,
    "max_delay_minutes": null,
    "delay_summary": "Closed to non-scheduled transient GA except PPR in demo data.",
    "arrival_runway": "19R/26L",
    "departure_runway": "19L/26R",
    "aar": 56,
    "metar_condition": "VFR",
    "flight_category": "VFR",
    "metar_wind": "19010KT",
    "metar_visibility": "10SM",
    "metar_observed_at": "2026-06-02T22:10:00Z",
    "taf_trend": "VFR",
    "taf_next_risk_window": "None",
    "overall_impact_color": "Red",
    "overall_impact_label": "Current Operational Impact",
    "last_updated_at": "2026-06-02T22:10:00Z",
    "freshness_status": "fresh",
    "source_summary": "Current Operational Impact \u2014 FAA NAS Status"
  },
  {
    "airport_id": "KLAX",
    "iata": "LAX",
    "icao": "KLAX",
    "region": "West Coast",
    "display_name": "Los Angeles",
    "airport_name": "Los Angeles International Airport",
    "city": "Los Angeles",
    "state": "CA",
    "latitude": 33.9416,
    "longitude": -118.4085,
    "dominant_sky_condition": "Partly Cloudy",
    "high_temperature_f": 70,
    "low_temperature_f": 60,
    "forecast_impact_color": "Green",
    "forecast_impact_label": "Good",
    "forecast_impact_reasons": "No major weather-impact language detected.",
    "forecast_icon_id": "30",
    "forecast_icon_url": "",
    "current_delay_type": "Airport Closure",
    "current_status_code": "CLOSURE",
    "current_reason": "GA restriction demo freeform",
    "avg_delay_minutes": null,
    "max_delay_minutes": null,
    "delay_summary": "Closed to non-scheduled transient GA except PPR in demo data.",
    "arrival_runway": "25L/24R",
    "departure_runway": "25R/24L",
    "aar": 66,
    "metar_condition": "VFR",
    "flight_category": "VFR",
    "metar_wind": "25009KT",
    "metar_visibility": "10SM",
    "metar_observed_at": "2026-06-02T22:10:00Z",
    "taf_trend": "VFR",
    "taf_next_risk_window": "None",
    "overall_impact_color": "Red",
    "overall_impact_label": "Current Operational Impact",
    "last_updated_at": "2026-06-02T22:10:00Z",
    "freshness_status": "fresh",
    "source_summary": "Current Operational Impact \u2014 FAA NAS Status"
  },
  {
    "airport_id": "KJFK",
    "iata": "JFK",
    "icao": "KJFK",
    "region": "Northeast",
    "display_name": "New York JFK",
    "airport_name": "John F. Kennedy International Airport",
    "city": "New York",
    "state": "NY",
    "latitude": 40.6413,
    "longitude": -73.7781,
    "dominant_sky_condition": "Chance Showers",
    "high_temperature_f": 72,
    "low_temperature_f": 58,
    "forecast_impact_color": "Amber",
    "forecast_impact_label": "Monitor",
    "forecast_impact_reasons": "Chance of showers may affect arrival spacing.",
    "forecast_icon_id": "39",
    "forecast_icon_url": "",
    "current_delay_type": "None",
    "current_status_code": "NORMAL",
    "current_reason": "No active FAA/NAS event in demo data",
    "avg_delay_minutes": null,
    "max_delay_minutes": null,
    "delay_summary": "No active operational impact in demo data.",
    "arrival_runway": "",
    "departure_runway": "",
    "aar": null,
    "metar_condition": "VFR",
    "flight_category": "VFR",
    "metar_wind": "18012KT",
    "metar_visibility": "10SM",
    "metar_observed_at": "2026-06-02T22:10:00Z",
    "taf_trend": "Showers possible",
    "taf_next_risk_window": "Afternoon",
    "overall_impact_color": "Amber",
    "overall_impact_label": "Forecast Weather Impact",
    "last_updated_at": "2026-06-02T22:10:00Z",
    "freshness_status": "fresh",
    "source_summary": "Forecast Weather Impact \u2014 NWS forecast proxy"
  },
  {
    "airport_id": "KORD",
    "iata": "ORD",
    "icao": "KORD",
    "region": "Great Lakes",
    "display_name": "Chicago O'Hare",
    "airport_name": "Chicago O'Hare International Airport",
    "city": "Chicago",
    "state": "IL",
    "latitude": 41.9742,
    "longitude": -87.9073,
    "dominant_sky_condition": "Mostly Sunny",
    "high_temperature_f": 76,
    "low_temperature_f": 55,
    "forecast_impact_color": "Green",
    "forecast_impact_label": "Good",
    "forecast_impact_reasons": "No major weather-impact language detected.",
    "forecast_icon_id": "34",
    "forecast_icon_url": "",
    "current_delay_type": "None",
    "current_status_code": "NORMAL",
    "current_reason": "No active FAA/NAS event in demo data",
    "avg_delay_minutes": null,
    "max_delay_minutes": null,
    "delay_summary": "No active operational impact in demo data.",
    "arrival_runway": "",
    "departure_runway": "",
    "aar": null,
    "metar_condition": "VFR",
    "flight_category": "VFR",
    "metar_wind": "27010KT",
    "metar_visibility": "10SM",
    "metar_observed_at": "2026-06-02T22:10:00Z",
    "taf_trend": "VFR",
    "taf_next_risk_window": "None",
    "overall_impact_color": "Green",
    "overall_impact_label": "Normal / Monitor",
    "last_updated_at": "2026-06-02T22:10:00Z",
    "freshness_status": "fresh",
    "source_summary": "Forecast Weather Impact \u2014 NWS forecast proxy"
  },
  {
    "airport_id": "KIAH",
    "iata": "IAH",
    "icao": "KIAH",
    "region": "Southern Plains",
    "display_name": "Houston Intercontinental",
    "airport_name": "George Bush Intercontinental Airport",
    "city": "Houston",
    "state": "TX",
    "latitude": 29.9902,
    "longitude": -95.3368,
    "dominant_sky_condition": "Thunderstorms Possible",
    "high_temperature_f": 90,
    "low_temperature_f": 74,
    "forecast_impact_color": "Amber",
    "forecast_impact_label": "Possible Delays",
    "forecast_impact_reasons": "Thunderstorm potential in terminal area.",
    "forecast_icon_id": "38",
    "forecast_icon_url": "",
    "current_delay_type": "None",
    "current_status_code": "NORMAL",
    "current_reason": "No active FAA/NAS event in demo data",
    "avg_delay_minutes": null,
    "max_delay_minutes": null,
    "delay_summary": "No active operational impact in demo data.",
    "arrival_runway": "",
    "departure_runway": "",
    "aar": null,
    "metar_condition": "VFR",
    "flight_category": "VFR",
    "metar_wind": "16012KT",
    "metar_visibility": "10SM",
    "metar_observed_at": "2026-06-02T22:10:00Z",
    "taf_trend": "VCTS later",
    "taf_next_risk_window": "Evening",
    "overall_impact_color": "Amber",
    "overall_impact_label": "Forecast Weather Impact",
    "last_updated_at": "2026-06-02T22:10:00Z",
    "freshness_status": "fresh",
    "source_summary": "Forecast Weather Impact \u2014 NWS forecast proxy"
  }
];
